name: CI MAIN

env:
  SHOPIFY_CLI_TTY: 0
  SHOPIFY_SHOP_STAGING: ${{ vars.SHOPIFY_SHOP_STAGING }}
  OXYGEN_DEPLOYMENT_TOKEN_STAGING: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_STAGING }}
  SHOPIFY_SHOP_PRODUCTION: ${{ vars.SHOPIFY_SHOP_PRODUCTION }}
  OXYGEN_DEPLOYMENT_TOKEN_PRODUCTION: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_PRODUCTION }}

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write
  id-token: write

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/jobs.lint.yml
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/jobs.test.yml
    secrets: inherit

  build:
    name: Build
    uses: ./.github/workflows/jobs.build.yml
    secrets: inherit
