name: CI

env:
  SHOPIFY_CLI_TTY: 0
  SHOPIFY_SHOP_STAGING: ${{ vars.SHOPIFY_SHOP_STAGING }}
  OXYGEN_DEPLOYMENT_TOKEN_STAGING: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_STAGING }}
  SHOPIFY_SHOP_PRODUCTION: ${{ vars.SHOPIFY_SHOP_PRODUCTION }}
  OXYGEN_DEPLOYMENT_TOKEN_PRODUCTION: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_PRODUCTION }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write
  id-token: write

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/jobs.lint.yml
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/jobs.test.yml
    secrets: inherit

  build:
    name: Build
    if: github.ref_name == github.event.repository.default_branch
    uses: ./.github/workflows/jobs.build.yml
    secrets: inherit

  deploy-staging-preview:
    name: Deploy staging preview
    needs: [test, lint]
    if: |
      github.event_name == 'pull_request' 
      && (startsWith(github.actor, 'dependabot') == false)
    uses: ./.github/workflows/jobs.deploy.yml
    with:
      preview: true
      environment: staging-preview
      message: ${{ github.event.pull_request.title }}

  deploy-prod-preview:
    name: Deploy production preview
    needs: [test, lint]
    if: |
      github.event_name == 'pull_request' 
      && (startsWith(github.actor, 'dependabot') == false)
    uses: ./.github/workflows/jobs.deploy.yml
    with:
      preview: true
      environment: production-preview
      message: ${{ github.event.pull_request.title }}
