name: CI

env:
  SHOPIFY_CLI_TTY: 0
  SHOPIFY_SHOP_STAGING: ${{ vars.SHOPIFY_SHOP_STAGING }}
  OXYGEN_DEPLOYMENT_TOKEN_STAGING: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_STAGING }}
  SHOPIFY_SHOP_PRODUCTION: ${{ vars.SHOPIFY_SHOP_PRODUCTION }}
  OXYGEN_DEPLOYMENT_TOKEN_PRODUCTION: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_PRODUCTION }}

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write
  id-token: write

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/jobs.lint.yml
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/jobs.test.yml
    secrets: inherit

  deploy-staging-preview:
    name: Build and Deploy staging preview
    uses: ./.github/workflows/jobs.deploy.yml
    with:
      preview: true
      environment: staging-preview
      message: ${{ github.event.pull_request.title }}

  deploy-prod-preview:
    name: Build and Deploy production preview
    uses: ./.github/workflows/jobs.deploy.yml
    with:
      preview: true
      environment: production-preview
      message: ${{ github.event.pull_request.title }}
